sudo: false
language: php

php:
  - 7.1
  - 7.2

env:
  global:
  - REPOSITORY_USER=wordhatautomation
  - secure: "ISejhHxnc5Al9rnmDdPhs6bNKwGmsMyoWXQfs/gX5y+w77Yp6z44GlRT3W+vWBjMt2wVdsjVv/wzU2T3yQst1+DVboMH0DkvkXJLI+epOnJOUYVEpvnCibidbgxTRCPNWdfQ+3k+/V2294N2lrJBM2sE5CBkAhuj48pwZUfyuqh9IvR5rhXnbr+iedXROPepRK5Lum8JIueUjvwbC0PfhdCGVlO/QCEl1CgOZFIH4B16V0atFYPT4AZjNTuLe9/yhAV8bbrwWM7TQkN6DmPpWcp5PvoNkK0sHl8mU+2u320bR4BPLFDUKUtYFbNL64KGfrC7vEu443NKcWRksn1W8d5kaaNewoT6yLZ8pEA9u9QmIy7pLvRRwHul6y21iNDQois+mssWNx/9PYa/17x9vp4tGPzL3vr4UT6g9AmcZIX43xBObMZSqO+9dJ5TpRvZAMMFx6tzSULZFATnRa3ru/zYPlXO82/lM4DBpVFCXuSfM+QRmII+puv4UrsueFzcATvVgWz/DNTYh8U4q8SlXoDpkDct4GCMOOkE9Os+BpOqZvuzC3KlKDYesYTVu/9Mhec3A3cBZb7UBqVUkrEMs8yc5hFA/QsenXCzEZwChnTGQmFikkXAoA5QM0oq0H7NONUfEceJmT3cKWfHhgd/YcmG8/QmYNmU54NBxFeyQ+A="
  matrix:
  - WORDHAT_DRIVER=wpphp
  - WORDHAT_DRIVER=wpcli

services:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files


notifications:
  email: false
  slack:
    secure: UKnkI42ZBwYosQbg12QjWP1Glmkbfp9S1vAkeFS4AO6nY3Lfd3GdSHX0CjGuKtLhzWXtiH4Euza3ZGNgOiQy69OZUHTo10fhk8vFdwdoiw0phiMUVWhcB9LLKgh4B768yTPtgoucyFfvgvFrCCKy065wMTvWWouekDp8gHZgOULi9KO1nPOvqqpCYMVBowheoPLkJ2iDZtbzgvCRyDISWirn322cheROZz/AfOpnYhU6jBGrjvb5QDvX0G5VVp9lDK2X0lMq4/yMIhT2w9RL3or7h0K066y1WJYZfmoxskyJjRHBmhegmqX6q57n4b5Bg83Ec80pNQ3mwknuncOVBjiAJIW09wgf5SP14U4hfOTD3soE+0ehjIsBIvtJnxNm2uddMrD9OoeAwZVtRY1XLEMhO4ISp5NjaJXSBreVnF43ytqoKJBwWUUIg5Bp1Sck4D9edMPeqW4yWqwkhDq/L6+PRZ7VoUy2e8mZsKSOL7Wb8RmtKfZhpCrEos5XFhaRA97ke9XaV6PJuN+2UCVPVOXGPrpJXosC0SWVl7Pj5Urd7EhwpPqVRWK3YJIk6VhLFuXNgbGj3KZNG6v+ETZknlxPB5T55i9ZCQ2Beoza0+epvpiPIuAbUzdRBAHz9j4LODfHmefeZaQ7kkjdgT7d+SV4v58lSZwYdH5mb1q4j7g=

install:
  # Install all of the dependencies you need here.
  - composer install --no-interaction --prefer-dist --no-progress

before_script:
  - sudo /etc/init.d/mysql stop

script:
  # Execute all of the commands which should make the build pass or fail.
  - find ./src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - composer phpcs
  - vendor/bin/phing -Dwordhat.php-version=${TRAVIS_PHP_VERSION} -Dwordhat.driver=${WORDHAT_DRIVER}
