sudo: false
language: php

php:
  - 7.0
  - 7.2

env:
  global:
  - REPOSITORY_USER=wordhatautomation
  - secure: "Y3OPzFhnNfiVfAc/r1gS554QwdFGEhNIqMfXnzwpgf6P7dOGf4nehpJwMfne4SMj6qhqgCuFHDkYr1DDeYf46Tn9DjQR7RyPB3ZkD7FhMhhcLVbezaXgbsZurfWsaeOrZge4N5lS/VH6xdyH1nwSUrCAdfUj7KqQNnVguMacBSzQ3WqDrmG9idZnJsiuQukfbiZ7bWT0WKVaKQxXKFjQl27g6o+9KpbVKxc5q2s8IM23OK6jc/T6pwc8jd7nJwTUMpig+il5oHfwlxywuVLCh34boRrVtcnZ2EBdiIDFn0hST/2dx2voOuo4DXOr8uyfkdGJisMdKmWrEv2vuM85tvnDiNnDrIy8o5mFIWT+9yON+FOF0ssqx8o0iMVyaElG1mZLNih6EQOxVpWi2p2XimVaB7VGds66X1bGSlPnpl/+4UC7iTg3nOojRUDvoCbexnZYsd3sDd51qQC2/UiYnLA8CLodLuh5CIRYSBqGuS5F7wIXMnoLjLGPMRGEyeeYMwMrnM0eGazLw4OUKhQyw/XAeT0v3yQ8LnpaD0B6a56uFF2j2ReEm2v/KLQEF30fooaZptWiP2+gXTLuQ//I2iLm0Wk1O8lpBqFzsGNdlQw5iqNQPzoO+NfadJTXjl+7h6gNmrK2+RJPA3qpvyGbvJlkFBHTOIgRSiRfOtPvMXI="
  matrix:
  - WORDHAT_DRIVER=wpphp
  - WORDHAT_DRIVER=wpcli

services:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files


notifications:
  email: false
  slack:
    secure: UKnkI42ZBwYosQbg12QjWP1Glmkbfp9S1vAkeFS4AO6nY3Lfd3GdSHX0CjGuKtLhzWXtiH4Euza3ZGNgOiQy69OZUHTo10fhk8vFdwdoiw0phiMUVWhcB9LLKgh4B768yTPtgoucyFfvgvFrCCKy065wMTvWWouekDp8gHZgOULi9KO1nPOvqqpCYMVBowheoPLkJ2iDZtbzgvCRyDISWirn322cheROZz/AfOpnYhU6jBGrjvb5QDvX0G5VVp9lDK2X0lMq4/yMIhT2w9RL3or7h0K066y1WJYZfmoxskyJjRHBmhegmqX6q57n4b5Bg83Ec80pNQ3mwknuncOVBjiAJIW09wgf5SP14U4hfOTD3soE+0ehjIsBIvtJnxNm2uddMrD9OoeAwZVtRY1XLEMhO4ISp5NjaJXSBreVnF43ytqoKJBwWUUIg5Bp1Sck4D9edMPeqW4yWqwkhDq/L6+PRZ7VoUy2e8mZsKSOL7Wb8RmtKfZhpCrEos5XFhaRA97ke9XaV6PJuN+2UCVPVOXGPrpJXosC0SWVl7Pj5Urd7EhwpPqVRWK3YJIk6VhLFuXNgbGj3KZNG6v+ETZknlxPB5T55i9ZCQ2Beoza0+epvpiPIuAbUzdRBAHz9j4LODfHmefeZaQ7kkjdgT7d+SV4v58lSZwYdH5mb1q4j7g=

install:
  # Install all of the dependencies you need here.
  - composer install --no-interaction --prefer-dist --no-progress

before_script:
  - sudo /etc/init.d/mysql stop

script:
  # Execute all of the commands which should make the build pass or fail.
  - find ./src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - composer phpcs
  - vendor/bin/phing -Dwordhat.php-version=${TRAVIS_PHP_VERSION} -Dwordhat.driver=${WORDHAT_DRIVER}
