parameters:
  wordpress.driver.blackbox.class: PaulGibbs\WordpressBehatExtension\Driver\Blackbox\BlackboxDriver

services:
  wordpress.driver.blackbox:
    class: "%wordpress.driver.blackbox.class%"
    tags:
      - { name: wordpress.driver, alias: blackbox }
